FROM ubuntu:22.04

WORKDIR /init

# 复制代码到容器
COPY install.sh /init/install.sh
COPY package.json /init/package.json

# 安装
RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" && \
    apt-get install -y bash wget curl micro unzip vim dmidecode git build-essential cmake libssl-dev libsdl1.2-compat-dev libavcodec-dev libavutil-dev ffmpeg

# 设置默认 shell 为 Bash
RUN usermod -s /bin/bash root

# 安装脚本
RUN sh /init/install.sh

# 启动卡住容器，防止容器退出
CMD ["tail", "-f", "/dev/null"]